### ISSUE TITLE
Svelteアプリをデプロイする

### ISSUE THREAD

**Issue by oshanQQ** [o-xian999/white-day-2021#4]
- デプロイしないとURLをもらえない
- URLを暗号にするので絶対にデプロイまでは必要

**Comment by o-xian999** [comment]
Sapper公式の説明
Exportについて
https://sapper.svelte.dev/docs#Exporting

**Comment by oshanQQ** [comment]
Deployに向けた大まかな操作(ページではNetlifyだけど、やることは一緒)
https://dev.to/sumitkharche/how-to-deploy-sapper-app-on-netlify-12en
